In [ ]:
import numpy as np

In [ ]:
arr=np.array([1,2,3])

In [11]:
arr

array([1, 2, 3])

In [12]:
a = [1,2,'wow']
a

[1, 2, 'wow']

In [15]:
np.array(a)

array(['1', '2', 'wow'], dtype='<U21')

In [18]:
l=[[1,2,3],[4,5,6],[7,8,9]]
np.array(l)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [21]:
arr=np.arange(1,11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [23]:
arr=np.zeros(6)
arr

array([0., 0., 0., 0., 0., 0.])

array([1., 1., 1.])

In [38]:
ar=np.ones((2,2))
ar

array([[1., 1.],
       [1., 1.]])

In [39]:
b = np.ones((2,5))
b

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [41]:
n=np.zeros((2,2))
n

array([[0., 0.],
       [0., 0.]])

In [46]:
arr=np.linspace(1,5,5)
arr

array([1., 2., 3., 4., 5.])

In [48]:
arr=np.linspace(0,0.5,12)
arr

array([0.        , 0.04545455, 0.09090909, 0.13636364, 0.18181818,
       0.22727273, 0.27272727, 0.31818182, 0.36363636, 0.40909091,
       0.45454545, 0.5       ])

In [52]:
arr=np.random.rand(10)
arr

array([0.01546069, 0.05322756, 0.29856066, 0.17548816, 0.44377679,
       0.65692318, 0.68905666, 0.58123504, 0.51787092, 0.12684105])

In [53]:
np.random.randn(10)

array([-1.33431218, -0.40826167,  0.23939623,  0.25372035, -0.47958993,
        0.28175964,  0.64584666, -0.22575256, -0.24929194, -0.32259019])

In [54]:
np.random.randn(10)

array([-0.51878944, -1.87258735,  0.79792484, -0.9936364 ,  0.81055341,
        0.46506294,  0.44982725, -0.96277099, -1.83117283,  0.35726049])

In [55]:
np.random.randn(10)

array([-0.54782341, -0.73072767, -0.29670982,  1.92245039, -1.24912066,
       -0.00430688,  0.35127757, -1.58136166,  0.79943926, -0.64956442])

In [56]:
np.random.randn(10)

array([ 1.5264264 , -1.29328379,  1.12617166, -1.72178336, -1.04555988,
       -0.57258515, -0.3798367 , -0.06464923, -0.8210788 ,  0.05432375])

In [58]:
np.random.randint(10)


4

In [59]:
np.random.randint(10)

2

In [62]:
np.random.randint(1,20,5)

array([ 5, 15,  6, 10, 15], dtype=int32)

In [72]:
# Attributes
arr=np.array([[1,2,3],[4,5,6],[7,8,9]])
arr.shape
arr.size
arr.dtype
arr.min()
arr.max()
arr.sum()


np.int64(9)

In [86]:
arr.mean()
arr.std()
arr.argmax()
arr.argmin()

np.int64(0)

In [101]:
arr=np.arange(1,31)
arr
arr.reshape(6,5)
arr.resize()

###### arr.reshape(,5)

In [100]:
arr.resize()

In [116]:
arr = np.arange(1,51)

arr = arr.reshape(10,5)

arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35],
       [36, 37, 38, 39, 40],
       [41, 42, 43, 44, 45],
       [46, 47, 48, 49, 50]])

In [119]:
ar = np.arange(1,101)
ar.reshape(10,10)

array([[  1,   2,   3,   4,   5,   6,   7,   8,   9,  10],
       [ 11,  12,  13,  14,  15,  16,  17,  18,  19,  20],
       [ 21,  22,  23,  24,  25,  26,  27,  28,  29,  30],
       [ 31,  32,  33,  34,  35,  36,  37,  38,  39,  40],
       [ 41,  42,  43,  44,  45,  46,  47,  48,  49,  50],
       [ 51,  52,  53,  54,  55,  56,  57,  58,  59,  60],
       [ 61,  62,  63,  64,  65,  66,  67,  68,  69,  70],
       [ 71,  72,  73,  74,  75,  76,  77,  78,  79,  80],
       [ 81,  82,  83,  84,  85,  86,  87,  88,  89,  90],
       [ 91,  92,  93,  94,  95,  96,  97,  98,  99, 100]])

In [127]:
# Indexing and Slicing
arr=np.arange(1,21)
arr



array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [136]:
# slice from 2 to 5
arr[1:10]

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10])

In [143]:
#slice from 13 to 19
arr[1::3]

array([ 2,  5,  8, 11, 14, 17, 20])

In [152]:
# Indexing and Slicing
arr = np.arange(1,21)
ar= arr.reshape(5,4)
ar


array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20]])

In [161]:
ar[4,2]

np.int64(19)

In [162]:
ar[2,1]

np.int64(10)

In [163]:
ar[2,3]

np.int64(12)

In [164]:
ar[3,2]

np.int64(15)

In [166]:
ar[0:2 ,1:3]

array([[2, 3],
       [6, 7]])

In [173]:
ar[2: ,0:]

array([[ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20]])

In [174]:
ar[3:,2]

array([15, 19])

In [182]:
# boolean indexing
arr= np.arange(1,21)


In [176]:
bool_indx = arr%2==0


array([False,  True, False,  True, False,  True, False,  True, False,
        True, False,  True, False,  True, False,  True, False,  True,
       False,  True])

In [183]:
a=arr[bool_indx]
a

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [184]:
# Array Operation
a1= np.array([1,2,3,4,5])
a1

array([1, 2, 3, 4, 5])

In [185]:
# Array Operation
a2= np.array([1,2,3,4,5])
a2

array([1, 2, 3, 4, 5])

In [187]:
a1[4]+a2[0]

np.int64(6)

In [191]:
l = [10,20,30,40,50]
add=np.array(l)
add+10

array([20, 30, 40, 50, 60])

In [193]:

x=np.arange(1,31)
x

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30])

In [194]:
x.reshape(6,5)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [195]:
x+9

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39])

In [197]:
#Deep and Sallow Copy
y= np.arange(1,31)
y

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30])

In [210]:
w=y[0:6] 
w

array([1, 2, 3, 4, 5, 6])

In [211]:
w*2

array([ 2,  4,  6,  8, 10, 12])

In [212]:
y

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30])

In [216]:
y[21:28]*10

array([220, 230, 240, 250, 260, 270, 280])

In [217]:
y

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30])

In [221]:
y
c=y
c

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30])

In [223]:
c[0]=100
c

array([100,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
        14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,
        27,  28,  29,  30])

In [224]:
y

array([100,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
        14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,
        27,  28,  29,  30])

In [235]:
e = np.arange(1,21)
e

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [239]:
e
s = e.copy()
s[0]=1000
s

array([1000,    2,    3,    4,    5,    6,    7,    8,    9,   10,   11,
         12,   13,   14,   15,   16,   17,   18,   19,   20])

In [240]:
e

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [242]:
#matrix operationa
m1 = np.arange(1,11)
m1


array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [249]:
m2=np.arange(1,11)
m2

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [262]:
m1.reshape(2,5).T

array([[ 1,  6],
       [ 2,  7],
       [ 3,  8],
       [ 4,  9],
       [ 5, 10]])

In [261]:
m2.reshape(5,2).T

array([[ 1,  3,  5,  7,  9],
       [ 2,  4,  6,  8, 10]])

In [255]:
m1 @ m2

np.int64(385)

In [258]:
np.dot(m1,m2)

np.int64(385)

In [259]:
m1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [260]:
m1.T

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
# Advance Array Manipulation
   # Stack and Spilit

In [273]:
# 1. Stack
f = np.array([1,2,3,4,5])
g = np.array([6,7,8,9,0])

In [274]:
np.vstack((f,g))

array([[1, 2, 3, 4, 5],
       [6, 7, 8, 9, 0]])

In [275]:
np.hstack((f,g))

array([1, 2, 3, 4, 5, 6, 7, 8, 9, 0])

In [277]:
np.column_stack((f,g))

array([[1, 6],
       [2, 7],
       [3, 8],
       [4, 9],
       [5, 0]])

In [278]:
np.row_stack((f,g))

C:\Users\Acer\AppData\Local\Temp\ipykernel_18836\851658626.py:1: DeprecationWarning: `row_stack` alias is deprecated. Use `np.vstack` directly.
  np.row_stack((f,g))


array([[1, 2, 3, 4, 5],
       [6, 7, 8, 9, 0]])

In [280]:
#  2. Spiliting Array
spilit = np.arange(16)
spilit.reshape(4,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [300]:
z=np.hsplit(spilit,4)
z

[array([0, 1, 2, 3]),
 array([4, 5, 6, 7]),
 array([ 8,  9, 10, 11]),
 array([12, 13, 14, 15])]

In [301]:
orr=np.vsplit(spilit,2)
for i in orr:
    print(i)

ValueError: vsplit only works on arrays of 2 or more dimensions

In [ ]:
# Exercise  

In [319]:
# 1. Valid Suduku
import numpy as np

board = np.array([
[5,3,4,6,7,8,9,1,2],
[6,7,2,1,9,5,3,4,8],
[1,9,8,3,4,2,5,6,7],
    
[8,5,9,7,6,1,4,2,3],
[4,2,6,8,5,3,7,9,1],
[7,1,3,9,2,4,8,5,6],
    
[9,6,1,5,3,7,2,8,4],
[2,8,7,4,1,9,6,3,5],
[3,4,5,2,8,6,1,7,9]
])
sum(board)
#board.sum()


array([45, 45, 45, 45, 45, 45, 45, 45, 45])

In [312]:
for i in board:
    print(len(set(i))==9)

True
True
True
True
True
True
True
True
True


In [314]:
for j in board.T:
    print(len(set(j))==9)

True
True
True
True
True
True
True
True
True


In [327]:
r = np.sum(board,axis=1)
for i in r:
    if i != 45:
        print("Suduko is invalid")
        break
    else:
        print("Valid")

Valid
Valid
Valid
Valid
Valid
Valid
Valid
Valid
Valid


In [331]:
c=np.sum(board,axis=0)
for i in c:
    if i != 45:
        print("invalid")
        break
    else:
        print("valid")

valid
valid
valid
valid
valid
valid
valid
valid
valid


In [332]:
np.sum(board[2: ,2:])

np.int64(246)

In [ ]:
# 2. Capston 

In [335]:
marks = np.array([
    [78, 85, 90],
    [67, 72, 80],
    [88, 91, 95],
    [56, 60, 65],
    [92, 89, 94]
])
marks

array([381, 397, 424])

In [338]:
marks.shape

(5, 3)

In [356]:
#avg = np.sum(marks[0:5,0:1],axis=0)
#avg.mean()

np.float64(381.0)

In [354]:
#marks[0:5, 0:1]

array([[78],
       [67],
       [88],
       [56],
       [92]])

In [357]:
avg = np.mean(marks, axis=1)
print(avg)

[84.33333333 73.         91.33333333 60.33333333 91.66666667]


In [358]:
avg = np.mean(marks)
print(avg)

80.13333333333334


In [359]:
avg = np.mean(marks[:,0])
print(avg)

76.2


In [360]:
np.mean(marks[:,0])

np.float64(76.2)

In [361]:
marks

array([[78, 85, 90],
       [67, 72, 80],
       [88, 91, 95],
       [56, 60, 65],
       [92, 89, 94]])

In [375]:
#marks[:,1]

array([85, 72, 91, 60, 89])

In [378]:
sci = marks[:,2]
sci.max()

np.int64(95)

In [399]:
marks[marks[:,1]>90]

array([[88, 91, 95]])

In [405]:
new = marks[:,1] + 5
new

array([90, 77, 96, 65, 94])

In [406]:
marks

array([[78, 85, 90],
       [67, 72, 80],
       [88, 91, 95],
       [56, 60, 65],
       [92, 89, 94]])

In [418]:
mkks =len(marks[marks[:,0]<90])
mkks

4

In [419]:
marks


array([[78, 85, 90],
       [67, 72, 80],
       [88, 91, 95],
       [56, 60, 65],
       [92, 89, 94]])

In [421]:
np.mean(marks[:,1])


np.float64(79.4)

In [426]:
np.mean(marks[:,2])

np.float64(84.8)

In [430]:
marks[:,1:]

array([[85, 90],
       [72, 80],
       [91, 95],
       [60, 65],
       [89, 94]])

In [432]:
marks

array([[78, 85, 90],
       [67, 72, 80],
       [88, 91, 95],
       [56, 60, 65],
       [92, 89, 94]])

In [431]:
np.mean(marks[:,1:],axis=0)

array([79.4, 84.8])

In [434]:
marks[(marks[:,1] >= 80) & (marks[:,2] >= 80)]

array([[78, 85, 90],
       [88, 91, 95],
       [92, 89, 94]])

In [435]:
marks[:,2]

array([90, 80, 95, 65, 94])

In [445]:
marks[:,2][marks[:,2] < 75] = 0
marks

array([[78, 85, 90],
       [67, 72, 80],
       [88, 91, 95],
       [56, 60,  0],
       [92, 89, 94]])